{
    'name': "Sincronización de órdenes con CRM Piédica.",
    'summary': "Sincronización de las órdenes de ventas de CRM con Odoo",
    'description': "",
    'category': 'Uncategorized',
    'version': '14.0.1',
    'depends': ['base', 'sale', 'mrp', 'sale_stock', 'portal_account_custom_fields'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/crm_confirm_send_views.xml',
        'views/crm_status_views.xml',
        'views/mat_color_views.xml',
        'views/mat_hardness_views.xml',
        'views/mat_material_subtype_views.xml',
        'views/mat_material_type_views.xml',
        'views/mat_shore_a_views.xml',
        'views/mrp_views.xml',
        'views/portal_templates.xml',
        'views/prod_design_type_views.xml',
        'views/prod_material_subtype_views.xml',
        'views/prod_prod_use_list_views.xml',
        'views/prod_production_type_views.xml',
        'views/prod_shape_list_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/sale_views.xml',
        'data/crm_status_data.xml',
        'data/mat_color_data.xml',
        'data/mat_hardness_data.xml',
        'data/mat_material_subtype_data.xml',
        'data/mat_material_type_data.xml',
        'data/mat_shore_a_data.xml',
        'data/prod_material_subtype_data.xml',
        'data/prod_design_type_data.xml',
        'data/prod_prod_use_list_data.xml',
        'data/prod_production_type_data.xml',
        'data/prod_shape_list_data.xml',
        'data/ir_config_parameter.xml'
    ]
}
